version: 2.1

commands:
  setup:
    description: Setup project for all further steps
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-v1-{{ arch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ arch }}-
      - run:
          name: Install Dependencies
          command: yarn --cache-folder ~/.yarn --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-v1-{{ arch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.yarn

jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - setup
      - run:
          name: Lint
          command: yarn lint
          when: always
      - run:
          name: Test
          command: yarn test
          when: always
  